### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by Sydney-o9** [eejahromi/EEJSelectMenu#2]
That's awesome - any ideas if this can or will be implemented in swift?

**Comment by eejahromi** [comment]
Yes! It can certainly be implemented in a Swift project. I will post instructions on how to do it in a little bit.  😀

**Comment by Sydney-o9** [comment]
That would be awesome @eejahromi

**Comment by eejahromi** [comment]
@Sydney-o9 The [instructions](https://github.com/eejahromi/EEJSelectMenu/blob/master/swiftInstructions.md) are up! Hope you find them helpful and thanks for your interest. 😀

**Comment by Sydney-o9** [comment]
You're the best @eejahromi !

**Comment by Sydney-o9** [comment]
Just tested this - works perfectly.
Also, if using pods like the following - we don't even need a bridging header file!

```
use_frameworks!
pod 'EEJSelectMenu'
```

**Comment by eejahromi** [comment]
🤔   wow, I don't know why I didn't think of that solution!
Thanks @Sydney-o9
